# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required

language: R
sudo: false
cache: packages

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-extra

notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - BOOTSTRAP_LATEX=""
